server:
  port : 8399
  
# Oracle Connect
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traveldb?serverTimezone=Asia/Seoul
    username: travel
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  devtools: 
    livereload:
      enabled: true

  # Jpa Setting
  jpa:  
    hibernate:
      ddl-auto: none  #none create update
    properties: 
      hibernate: 
        default_batch_fetch_size: 500 
      show_sql:   true    # System.out 에 하이버네이트 실행 SQL
      format_sql: true

  # view Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  # gmail Transfer
  mail: 
    host: smtp.gmail.com
    port: 587
    username: lswhy8120@gmail.com
    password: myjbpfbbreulnwin
    properties: 
      mail: 
       smtp:
        auth: true
        starttls.enable: true
  
  
# Mybatis
mybatis: 
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
            
logging.level: 
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL
